2023-10-09 09:59:05,101 INFO    MainThread:3091363 [wandb_setup.py:_flush():75] Loading settings from /home/tg22/.config/wandb/settings
2023-10-09 09:59:05,102 INFO    MainThread:3091363 [wandb_setup.py:_flush():75] Loading settings from /home/tg22/remote-pycharm/plant/training/PlanT/outputs/training/DEBUG/2023-10-09_09-58-41/wandb/settings
2023-10-09 09:59:05,102 INFO    MainThread:3091363 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2023-10-09 09:59:05,102 INFO    MainThread:3091363 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'training/PlanT/lit_train.py', 'program': '/home/tg22/remote-pycharm/plant/training/PlanT/lit_train.py'}
2023-10-09 09:59:05,102 INFO    MainThread:3091363 [wandb_init.py:_log_setup():386] Logging user logs to /home/tg22/remote-pycharm/plant/training/PlanT/outputs/training/DEBUG/2023-10-09_09-58-41/wandb/run-20231009_095905-1uc7ospk/logs/debug.log
2023-10-09 09:59:05,102 INFO    MainThread:3091363 [wandb_init.py:_log_setup():387] Logging internal logs to /home/tg22/remote-pycharm/plant/training/PlanT/outputs/training/DEBUG/2023-10-09_09-58-41/wandb/run-20231009_095905-1uc7ospk/logs/debug-internal.log
2023-10-09 09:59:05,102 INFO    MainThread:3091363 [wandb_init.py:init():420] calling init triggers
2023-10-09 09:59:05,102 INFO    MainThread:3091363 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {'user': {'working_dir': '/home/tg22/remote-pycharm/plant'}, 'model': {'name': 'PlanT', 'training': {'max_epochs': 50, 'batch_size': 32, 'learning_rate': 0.0001, 'betas': [0.9, 0.95], 'grad_norm_clip': 1.0, 'weight_decay': 0.1, 'ckpt_path': 'log/', 'num_workers': 12, 'pred_len': 4, 'seq_len': 1, 'max_NextRouteBBs': 2, 'input_ego': False, 'remove_velocity': 'None', 'route_only_wp': False, 'remove_back': False, 'pretraining_path': 'none'}, 'pre_training': {'pretraining': 'forecast', 'multitask': True, 'forecastLoss_weight': 1, 'future_timestep': 1, 'quantize': True, 'precision_pos': 7, 'precision_speed': 4, 'precision_angle': 5}, 'network': {'hf_checkpoint': 'prajjwal1/bert-medium', 'embd_pdrop': 0.1}}, 'exp_folder_name': 'training', 'lrDecay_epoch': 46, 'seed': 1234, 'debug': False, 'visualize': True, 'overfit': 0, 'resume': True, 'use_caching': True, 'custom_sampler': False, 'gpus': 1, 'trainset_size': 3, 'benchmark': 'longest6', 'expname': 'DEBUG', 'wandb_name': 'training_PlanT_', 'save_dir': 'outputs/training/DEBUG//2023-10-09_09-58-41', 'data_dir': '/workspace/tg22/plant_dataset/data/PlanT/PlanT_data_1'}
2023-10-09 09:59:05,103 INFO    MainThread:3091363 [wandb_init.py:init():471] starting backend
2023-10-09 09:59:05,103 INFO    MainThread:3091363 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-09 09:59:05,110 INFO    MainThread:3091363 [backend.py:ensure_launched():219] starting backend process...
2023-10-09 09:59:05,115 INFO    MainThread:3091363 [backend.py:ensure_launched():225] started backend process with pid: 3091671
2023-10-09 09:59:05,117 INFO    MainThread:3091363 [wandb_init.py:init():480] backend started and connected
2023-10-09 09:59:05,122 INFO    MainThread:3091363 [wandb_init.py:init():550] updated telemetry
2023-10-09 09:59:05,139 INFO    MainThread:3091363 [wandb_init.py:init():581] communicating current version
2023-10-09 09:59:06,438 INFO    MainThread:3091363 [wandb_init.py:init():586] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-10-09 09:59:06,438 INFO    MainThread:3091363 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2023-10-09 09:59:36,440 INFO    MainThread:3091363 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2023-10-09 09:59:36,440 ERROR   MainThread:3091363 [wandb_init.py:init():601] backend process timed out
2023-10-09 09:59:36,440 ERROR   MainThread:3091363 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-10-09 09:59:36,452 ERROR   MainThread:3091363 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "/home/tg22/.conda/envs/plant/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/home/tg22/.conda/envs/plant/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 614, in init
    backend.cleanup()
  File "/home/tg22/.conda/envs/plant/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.interface.join()
  File "/home/tg22/.conda/envs/plant/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/tg22/.conda/envs/plant/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/tg22/.conda/envs/plant/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/tg22/.conda/envs/plant/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/tg22/.conda/envs/plant/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
